locations = ['london', 'dhaka', 'rome', 'new york', 'chitagong', 'tokyo']
popped_location = locations.pop()
popped_index_location = locations.pop(3)
print(popped_location)
print(popped_index_location)
print(locations)
locations.sort()
print(locations)
locations.reverse()
print(locations)
locations.insert(2, 'bayern')
print(locations)
locations.append('mumbai')
print(locations)
print(sorted(locations))
print(len(locations))